# Generated by Django 5.1.7 on 2026-04-17 00:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProjection',
            fields=[
                ('deposit_id', models.UUIDField(primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency', models.CharField(default='USD', max_length=20)),
                ('status', models.CharField(default='initiated', max_length=50)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_event_version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('created_at', 'version'),
                'unique_together': {('aggregate_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WalletProjection',
            fields=[
                ('wallet_id', models.UUIDField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('addresses', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=50)),
                ('last_event_version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalProjection',
            fields=[
                ('withdrawal_id', models.UUIDField(primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency', models.CharField(default='USD', max_length=20)),
                ('status', models.CharField(default='initiated', max_length=50)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_event_version', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
