# Generated by Django 5.1.7 on 2026-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'is_used', 'created_at'], name='accounts_ot_user_id_b1702a_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code'], name='accounts_ot_code_e43106_idx'),
        ),
    ]
